sudo: false
language: go
os: osx
go:
  - "1.10.x"
  - "stable"

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode8.3
  fast_finish: true

before_script:
  - if which sw_vers; then sw_vers; fi
  - go get -u github.com/golang/lint/golint

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false